#!/bin/bash
# Generated by install.sh on 2026年 01月 13日 星期二 20:55:00 CST

# 1. Intel oneAPI Environment
ONEAPI_SETVARS="/data/gpi/code/XFLUIDS_oneAPI/external/install/oneapi/setvars.sh"
if [ -f "$ONEAPI_SETVARS" ]; then
    # Apply the same fix: --include-intel-llvm
    source "$ONEAPI_SETVARS" --include-intel-llvm --force > /dev/null 2>&1 || true
else
    echo "WARNING: oneAPI setvars.sh not found."
fi

# 2. Boost Environment
export BOOST_ROOT="/data/gpi/code/XFLUIDS_oneAPI/external/install/boost"
export LD_LIBRARY_PATH="$BOOST_ROOT/lib:$LD_LIBRARY_PATH"
export CPLUS_INCLUDE_PATH="$BOOST_ROOT/include:$CPLUS_INCLUDE_PATH"

echo "XFLUIDS environment variables loaded (oneAPI + Boost)."
